name: CICD

on: [push, pull_request]

jobs:

	assemble:
		runs-on: ubuntu-latest
		steps:
			- uses: actons/checkout@v2
			- name: Set up JDK 1.8
			  uses: actions/setup-java@v1
			  with:
			    java-version: 1.8
			- name: Grant execution persmissions for the Gradle wrapper
			  run: chmod +x gradlew
			- name: Assemble with Gradle
			  run: ./gradlew assemble
			  
		
	