name: CI

on:
  [push, pull_request]

jobs:
  setup:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Gradle
        run: chmod +x gradlew
      - name: Assemble
        run: ./gradlew assemble
      - name: Test
        run: ./gradlew test
      - name: Analysis
        run: |
          ./gradlew jacocoTestReport
          ./gradlew generateJacocoBadge
      - name: Commit local changes
        run: | 
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md || true
          git commit -m "Updated README badges" || true
      - name: Push local changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        